import { css } from "styled-system/css";

/** Mobile menu styles generated by Panda CSS. */
export const styles = css({
  display: "contents",

  sm: {
    display: "none",
  },

  "& [data-slot='button']": {
    gridColumn: "2",
    gridRow: "1",
    justifySelf: "end",
  },

  "& [data-slot='nav']": {
    display: "grid",
    gridColumn: "1 / -1",
    gridRow: "2",
    gridTemplateRows: "0fr",
    minW: "0",
    opacity: "0",
    overflow: "hidden",
    pointerEvents: "none",
    transform: "translateY(-0.5rem)",
    transition:
      "grid-template-rows 220ms ease, opacity 180ms ease, transform 220ms ease, visibility 0s linear 220ms",
    visibility: "hidden",
  },

  "&[data-menu-open='true'] [data-slot='nav']": {
    gridTemplateRows: "1fr",
    opacity: "1",
    pointerEvents: "auto",
    transform: "translateY(0)",
    transition:
      "grid-template-rows 220ms ease, opacity 180ms ease, transform 220ms ease, visibility 0s linear 0s",
    visibility: "visible",
  },

  "& [data-slot='nav-list']": {
    display: "flex",
    alignItems: "stretch",
    flexDirection: "column",
    gap: "2",
    listStyle: "none",
    m: "0",
    minH: "0",
    overflow: "hidden",
    p: "0",
    width: "100%",
  },

  "&[data-menu-open='true'] [data-slot='nav-list']": {
    pt: "3",
  },

  "& [data-slot='link']": {
    display: "inline-flex",
    alignItems: "center",
    borderRadius: "sm",
    color: "text.secondary",
    fontSize: "sm",
    fontWeight: "medium",
    lineHeight: "1.25",
    minH: "11",
    px: "3",
    py: "2",
    transition: "color 150ms ease",

    _hover: {
      color: "text.primary",
    },

    _focusVisible: {
      bg: "background.page",
      boxShadow: "inset 0 0 0 2px token(colors.accent.blue)",
      color: "text.primary",
      outline: "none",
    },
  },

  "& [data-slot='cta-item']": {
    pt: "3",
  },

  "& [data-slot='cta']": {
    width: "100%",
  },

  "@media (prefers-reduced-motion: reduce)": {
    "& [data-slot='nav']": {
      transform: "none",
      transition: "none",
    },
  },
});
