import { css } from "styled-system/css";

/** Mobile menu styles generated by Panda CSS. */
export const styles = css({
  display: "contents",

  sm: {
    display: "none",
  },

  "& [data-slot='button']": {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    border: "1px solid",
    borderColor: "transparent",
    borderRadius: "full",
    gridColumn: "2",
    gridRow: "1",
    justifySelf: "end",
    bg: "transparent",
    color: "gray.950",
    lineHeight: "1",
    h: "11",
    p: "0",
    transition: "background-color 150ms ease, color 150ms ease",
    w: "11",

    _hover: {
      bg: "gray.100",
    },

    _focusVisible: {
      outline: "2px solid",
      outlineColor: "gray.950",
      outlineOffset: "3px",
    },
  },

  "&[data-menu-open='true'] [data-slot='button']": {
    bg: "gray.950",
    color: "white",

    _hover: {
      bg: "gray.800",
    },
  },

  "& [data-slot='icon']": {
    flexShrink: "0",
    pointerEvents: "none",
  },

  "& [data-slot='nav']": {
    display: "grid",
    gridColumn: "1 / -1",
    gridRow: "2",
    gridTemplateRows: "0fr",
    minW: "0",
    opacity: "0",
    overflow: "hidden",
    pointerEvents: "none",
    transform: "translateY(-0.5rem)",
    transition:
      "grid-template-rows 220ms ease, opacity 180ms ease, transform 220ms ease, visibility 0s linear 220ms",
    visibility: "hidden",
  },

  "&[data-menu-open='true'] [data-slot='nav']": {
    gridTemplateRows: "1fr",
    opacity: "1",
    pointerEvents: "auto",
    transform: "translateY(0)",
    transition:
      "grid-template-rows 220ms ease, opacity 180ms ease, transform 220ms ease, visibility 0s linear 0s",
    visibility: "visible",
  },

  "& [data-slot='nav-list']": {
    display: "flex",
    alignItems: "stretch",
    flexDirection: "column",
    gap: "2",
    listStyle: "none",
    m: "0",
    minH: "0",
    overflow: "hidden",
    p: "0",
    width: "100%",
  },

  "&[data-menu-open='true'] [data-slot='nav-list']": {
    pt: "3",
  },

  "& [data-slot='link']": {
    display: "flex",
    alignItems: "center",
    borderRadius: "sm",
    color: "gray.600",
    fontSize: "sm",
    fontWeight: "medium",
    lineHeight: "1.25",
    minH: "11",
    px: "3",
    py: "2",
    transition: "color 150ms ease",
    width: "100%",

    _hover: {
      color: "gray.950",
    },

    _focusVisible: {
      bg: "gray.50",
      boxShadow: "inset 0 0 0 2px token(colors.gray.950)",
      color: "gray.950",
      outline: "none",
    },
  },

  "& [data-slot='cta']": {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    border: "1px solid",
    borderColor: "gray.900",
    borderRadius: "full",
    color: "gray.950",
    fontSize: "sm",
    fontWeight: "semibold",
    lineHeight: "1",
    minH: "11",
    px: "4",
    py: "2.5",
    textAlign: "center",
    transition: "background-color 150ms ease, color 150ms ease",

    _hover: {
      bg: "gray.950",
      color: "white",
    },

    _focusVisible: {
      outline: "2px solid",
      outlineColor: "gray.950",
      outlineOffset: "2px",
    },
  },

  "@media (prefers-reduced-motion: reduce)": {
    "& [data-slot='nav']": {
      transform: "none",
      transition: "none",
    },
  },
});
