import { cva, type RecipeVariant } from "styled-system/css";

/** Shared button recipe generated by Panda CSS. */
export const buttonRecipe = cva({
  base: {
    appearance: "none",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    border: "1px solid",
    borderRadius: "full",
    boxSizing: "border-box",
    fontFamily: "inherit",
    fontWeight: "semibold",
    lineHeight: "1",
    minW: "0",
    textAlign: "center",
    textDecoration: "none",
    transition: "background-color 150ms ease, border-color 150ms ease, color 150ms ease",
    userSelect: "none",
    verticalAlign: "middle",
    whiteSpace: "nowrap",

    _enabled: {
      cursor: "pointer",
    },

    _disabled: {
      cursor: "not-allowed",
    },

    _focusVisible: {
      outline: "2px solid",
      outlineColor: "accent.blue",
      outlineOffset: "3px",
    },

    "&:disabled:not([data-loading='true'])": {
      opacity: "0.56",
    },

    "&[data-loading='true']": {
      cursor: "wait",
    },

    "& [data-slot='content']": {
      display: "inline-flex",
      alignItems: "center",
      minW: "0",
    },

    "& [data-slot='icon'], & [data-slot='icon-left'], & [data-slot='icon-right']": {
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      flexShrink: "0",
      pointerEvents: "none",
    },

    "& [data-slot='icon-right']": {
      transition: "transform 180ms ease",
    },

    "&[data-icon-motion='slide-right']:is(:hover, :focus-visible):not(:disabled) [data-slot='icon-right']":
      {
        transform: "translateX(0.25rem)",
      },

    "& [data-slot='spinner']": {
      display: "inline-block",
      border: "2px solid",
      borderColor: "currentColor",
      borderRadius: "full",
      borderTopColor: "transparent",
      flexShrink: "0",
      pointerEvents: "none",
      animation: "spin",
    },

    "@media (prefers-reduced-motion: reduce)": {
      transition: "none",

      "& [data-slot='icon-right']": {
        transition: "none",
      },

      "&[data-icon-motion='slide-right']:is(:hover, :focus-visible):not(:disabled) [data-slot='icon-right']":
        {
          transform: "none",
        },

      "& [data-slot='spinner']": {
        animation: "none",
      },
    },
  },
  variants: {
    size: {
      sm: {
        gap: "1.5",
        fontSize: "sm",
        minH: "9",
        px: "3",
        py: "2",

        "& [data-slot='icon'], & [data-slot='icon-left'], & [data-slot='icon-right'], & [data-slot='spinner']":
          {
            h: "4",
            w: "4",
          },
      },
      md: {
        gap: "2",
        fontSize: "sm",
        minH: "11",
        px: "4",
        py: "2.5",

        "& [data-slot='icon'], & [data-slot='icon-left'], & [data-slot='icon-right'], & [data-slot='spinner']":
          {
            h: "4",
            w: "4",
          },
      },
      lg: {
        gap: "2.5",
        fontSize: "md",
        minH: "12",
        px: "5",
        py: "3",

        "& [data-slot='icon'], & [data-slot='icon-left'], & [data-slot='icon-right'], & [data-slot='spinner']":
          {
            h: "5",
            w: "5",
          },
      },
    },
    variant: {
      solid: {},
      outline: {},
      ghost: {},
    },
    color: {
      primary: {},
      blue: {},
      green: {},
    },
    shape: {
      content: {},
      icon: {
        flexShrink: "0",
        p: "0",
      },
    },
  },
  compoundVariants: [
    {
      shape: "icon",
      size: "sm",
      css: {
        h: "9",
        px: "0",
        py: "0",
        w: "9",
      },
    },
    {
      shape: "icon",
      size: "md",
      css: {
        h: "11",
        px: "0",
        py: "0",
        w: "11",
      },
    },
    {
      shape: "icon",
      size: "lg",
      css: {
        h: "12",
        px: "0",
        py: "0",
        w: "12",
      },
    },
    {
      variant: "solid",
      color: "primary",
      css: {
        bg: "text.primary",
        borderColor: "text.primary",
        color: "background.page",

        "&:not(:disabled):hover": {
          bg: "accent.blue",
          borderColor: "accent.blue",
        },
      },
    },
    {
      variant: "solid",
      color: "blue",
      css: {
        bg: "accent.blue",
        borderColor: "accent.blue",
        color: "background.page",

        "&:not(:disabled):hover": {
          bg: "text.primary",
          borderColor: "text.primary",
        },
      },
    },
    {
      variant: "solid",
      color: "green",
      css: {
        bg: "accent.green",
        borderColor: "accent.green",
        color: "text.primary",

        "&:not(:disabled):hover": {
          bg: "text.primary",
          borderColor: "text.primary",
          color: "background.page",
        },
      },
    },
    {
      variant: "outline",
      color: "primary",
      css: {
        bg: "transparent",
        borderColor: "text.primary",
        color: "text.primary",

        "&:not(:disabled):hover": {
          bg: "text.primary",
          color: "background.page",
        },
      },
    },
    {
      variant: "outline",
      color: "blue",
      css: {
        bg: "transparent",
        borderColor: "accent.blue",
        color: "accent.blue",

        "&:not(:disabled):hover": {
          bg: "accent.blue",
          color: "background.page",
        },
      },
    },
    {
      variant: "outline",
      color: "green",
      css: {
        bg: "transparent",
        borderColor: "accent.green",
        color: "text.primary",

        "&:not(:disabled):hover": {
          bg: "accent.green",
        },
      },
    },
    {
      variant: "ghost",
      color: "primary",
      css: {
        bg: "transparent",
        borderColor: "transparent",
        color: "text.primary",

        "&:not(:disabled):hover": {
          bg: "color-mix(in srgb, token(colors.text.primary) 8%, transparent)",
        },
      },
    },
    {
      variant: "ghost",
      color: "blue",
      css: {
        bg: "transparent",
        borderColor: "transparent",
        color: "accent.blue",

        "&:not(:disabled):hover": {
          bg: "color-mix(in srgb, token(colors.accent.blue) 10%, transparent)",
        },
      },
    },
    {
      variant: "ghost",
      color: "green",
      css: {
        bg: "transparent",
        borderColor: "transparent",
        color: "text.primary",

        "&:not(:disabled):hover": {
          bg: "color-mix(in srgb, token(colors.accent.green) 16%, transparent)",
        },
      },
    },
  ],
  defaultVariants: {
    color: "primary",
    shape: "content",
    size: "md",
    variant: "solid",
  },
});

/** Variant values inferred from the shared button recipe. */
type ButtonRecipeVariant = RecipeVariant<typeof buttonRecipe>;

/** Visual treatment available for the shared button. */
export type ButtonVariant = ButtonRecipeVariant["variant"];

/** Color role available for the shared button. */
export type ButtonColor = ButtonRecipeVariant["color"];

/** Size available for the shared button. */
export type ButtonSize = ButtonRecipeVariant["size"];

/** Right-icon motion available for buttons with directional CTAs. */
export type ButtonIconMotion = "slide-right";
