import { css } from "styled-system/css";

/** Services section styles generated by Panda CSS. */
export const styles = css({
  bg: "color-mix(in srgb, token(colors.border.subtle) 12%, token(colors.background.page))",
  borderBottom: "1px solid",
  borderColor: "border.subtle",

  "& [data-slot='inner']": {
    display: "grid",
    gap: "8",
    py: "12",

    md: {
      gap: "10",
      py: "16",
    },
  },

  "& [data-slot='heading']": {
    maxW: "47rem",
    minW: "0",
    mx: "auto",
    textAlign: "center",
  },

  "& h2": {
    color: "text.primary",
    fontSize: "3xl",
    fontWeight: "bold",
    letterSpacing: "normal",
    lineHeight: "1.12",
    m: "0",
    overflowWrap: "anywhere",

    md: {
      fontSize: "4xl",
    },
  },

  "& [data-slot='description']": {
    color: "text.secondary",
    fontSize: "md",
    lineHeight: "1.65",
    m: "0",
    maxW: "43rem",
    mt: "4",
    mx: "auto",
  },

  "& [data-slot='list']": {
    display: "grid",
    gap: "4",
    gridTemplateColumns: "minmax(0, 1fr)",
    listStyle: "none",
    m: "0",
    p: "0",

    md: {
      gap: "4",
      gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    },

    "@media (min-width: 64rem)": {
      gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
    },
  },

  "& [data-slot='item']": {
    display: "grid",
    alignItems: "start",
    alignContent: "start",
    bg: "background.page",
    border: "1px solid",
    borderColor: "color-mix(in srgb, token(colors.border.subtle) 54%, transparent)",
    borderRadius: "lg",
    boxShadow: "0 8px 22px color-mix(in srgb, token(colors.text.primary) 4%, transparent)",
    gap: "5",
    gridTemplateColumns: "minmax(0, 1fr)",
    minH: "15.75rem",
    minW: "0",
    p: "6",
  },

  "& [data-slot='icon']": {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    bg: "color-mix(in srgb, token(colors.accent.blue) 14%, transparent)",
    borderRadius: "full",
    color: "accent.blue",
    flexShrink: "0",
    h: "14",
    w: "14",
  },

  "& [data-slot='item']:nth-child(2) [data-slot='icon'], & [data-slot='item']:nth-child(4) [data-slot='icon']":
    {
      bg: "color-mix(in srgb, token(colors.accent.green) 15%, transparent)",
      color: "accent.green",
    },

  "& [data-slot='icon'] svg": {
    h: "7",
    w: "7",
  },

  "& [data-slot='item-copy']": {
    minW: "0",
  },

  "& h3": {
    color: "text.primary",
    fontSize: "xl",
    fontWeight: "bold",
    lineHeight: "1.28",
    m: "0",
    overflowWrap: "anywhere",
  },

  "& [data-slot='item-copy'] p": {
    color: "text.secondary",
    fontSize: "md",
    lineHeight: "1.6",
    m: "0",
    mt: "3",
  },
});
