import { css } from "styled-system/css";

/** Skip link styles generated by Panda CSS. */
export const styles = css({
  bg: "text.primary",
  border: "1px solid",
  borderColor: "text.primary",
  borderRadius: "full",
  color: "background.page",
  fontSize: "sm",
  fontWeight: "semibold",
  left: "4",
  lineHeight: "1.2",
  minH: "11",
  opacity: "0",
  px: "4",
  py: "2.5",
  position: "fixed",
  textDecoration: "none",
  top: "4",
  transform: "translateY(-150%)",
  transition: "opacity 150ms ease, transform 150ms ease",
  zIndex: "100",

  _focusVisible: {
    opacity: "1",
    outline: "2px solid",
    outlineColor: "accent.blue",
    outlineOffset: "3px",
    transform: "translateY(0)",
  },

  "@media (prefers-reduced-motion: reduce)": {
    transition: "none",
  },
});
