import { css } from "styled-system/css";

/** Hero section styles generated by Panda CSS. */
export const styles = css({
  bg: "background.page",
  borderBottom: "1px solid",
  borderColor: "border.subtle",

  "& [data-slot='inner']": {
    display: "grid",
    alignItems: "center",
    gap: "10",
    py: "14",

    md: {
      py: "18",
    },

    "@media (min-width: 64rem)": {
      gridTemplateColumns: "minmax(0, 0.74fr) minmax(0, 1.06fr)",
      py: "20",
    },
  },

  "& [data-slot='content']": {
    maxW: "50rem",
    minW: "0",

    "@media (min-width: 64rem)": {
      maxW: "42rem",
    },
  },

  "& h1": {
    color: "text.primary",
    fontSize: "4xl",
    fontWeight: "bold",
    letterSpacing: "normal",
    lineHeight: "1.05",
    m: "0",
    maxW: "13ch",
    overflowWrap: "anywhere",

    sm: {
      fontSize: "5xl",
    },

    md: {
      fontSize: "6xl",
    },
  },

  "& [data-slot='description']": {
    color: "text.secondary",
    fontSize: "lg",
    lineHeight: "1.65",
    m: "0",
    maxW: "42rem",
    mt: "5",
  },

  "& [data-slot='actions']": {
    display: "flex",
    alignItems: "stretch",
    flexDirection: "column",
    gap: "3",
    mt: "7",

    sm: {
      alignItems: "center",
      flexDirection: "row",
      flexWrap: "wrap",
    },
  },
});
