import { css } from "styled-system/css";

/** Decorative hero visual styles generated by Panda CSS. */
export const styles = css({
  display: "block",
  h: "14rem",
  justifySelf: "center",
  maxW: "100%",
  minW: "0",
  overflow: "visible",
  position: "relative",
  userSelect: "none",
  w: "100%",

  "@media (min-width: 24rem)": {
    h: "15.7rem",
  },

  "@media (min-width: 28rem)": {
    h: "17.4rem",
  },

  sm: {
    h: "22.4rem",
  },

  md: {
    h: "28rem",
  },

  "@media (min-width: 64rem)": {
    h: "21.85rem",
    justifySelf: "end",
    maxW: "40rem",
  },

  "@media (min-width: 70rem)": {
    h: "25.2rem",
  },

  "@media (min-width: 75rem)": {
    h: "28rem",
  },

  "& [data-slot='canvas']": {
    h: "28rem",
    left: "50%",
    position: "absolute",
    top: "0",
    transform: "translateX(-50%) scale(0.5)",
    transformOrigin: "top center",
    w: "40rem",

    "@media (min-width: 24rem)": {
      transform: "translateX(-50%) scale(0.56)",
    },

    "@media (min-width: 28rem)": {
      transform: "translateX(-50%) scale(0.62)",
    },

    sm: {
      transform: "translateX(-50%) scale(0.8)",
    },

    md: {
      transform: "translateX(-50%) scale(1)",
    },

    "@media (min-width: 64rem)": {
      left: "0",
      transform: "scale(0.78)",
      transformOrigin: "top left",
    },

    "@media (min-width: 70rem)": {
      transform: "scale(0.9)",
    },

    "@media (min-width: 75rem)": {
      left: "0",
      transform: "none",
    },
  },

  "& [data-slot='browser']": {
    bg: "background.page",
    border: "1px solid",
    borderColor: "border.default",
    borderRadius: "lg",
    boxShadow: "0 8px 18px color-mix(in srgb, token(colors.text.primary) 5%, transparent)",
    h: "22.75rem",
    overflow: "hidden",
    position: "absolute",
    right: "2.75rem",
    top: "1.5rem",
    w: "30.5rem",
  },

  "& [data-slot='browser-bar']": {
    display: "flex",
    alignItems: "center",
    gap: "2",
    bg: "text.primary",
    h: "8",
    px: "3.5",
  },

  "& [data-slot='browser-dot']": {
    bg: "color-mix(in srgb, token(colors.background.page) 78%, transparent)",
    borderRadius: "full",
    h: "2.5",
    w: "2.5",
  },

  "& [data-slot='toolbar']": {
    display: "flex",
    alignItems: "center",
    gap: "2",
    borderBottom: "1px solid",
    borderColor: "border.subtle",
    h: "9",
    px: "3.5",
  },

  "& [data-slot='toolbar-arrow']": {
    borderLeft: "2px solid",
    borderTop: "2px solid",
    borderColor: "color-mix(in srgb, token(colors.border.default) 62%, transparent)",
    flexShrink: "0",
    h: "2.5",
    transform: "rotate(-45deg)",
    w: "2.5",
  },

  "& [data-slot='toolbar-arrow'] + [data-slot='toolbar-arrow']": {
    transform: "rotate(135deg)",
  },

  "& [data-slot='address']": {
    display: "inline-flex",
    alignItems: "center",
    alignSelf: "center",
    gap: "1.5",
    bg: "color-mix(in srgb, token(colors.border.subtle) 20%, transparent)",
    borderRadius: "full",
    color: "text.secondary",
    fontSize: "xs",
    fontWeight: "semibold",
    h: "6",
    lineHeight: "1",
    minW: "0",
    px: "3",
    whiteSpace: "nowrap",
    w: "13.5rem",
  },

  "& [data-slot='address'] svg": {
    color: "border.default",
    flexShrink: "0",
  },

  "& [data-slot='toolbar-lines']": {
    display: "grid",
    gap: "1.5",
    ml: "auto",
    w: "9",
  },

  "& [data-slot='toolbar-lines'] span": {
    bg: "border.subtle",
    borderRadius: "full",
    h: "1.5",
  },

  "& [data-slot='page']": {
    display: "grid",
    gridTemplateColumns: "1fr 0.8fr",
    gap: "3",
    p: "4",
  },

  "& [data-slot='media']": {
    bg: "linear-gradient(135deg, color-mix(in srgb, token(colors.accent.blue) 12%, transparent), color-mix(in srgb, token(colors.accent.blue) 4%, transparent))",
    borderRadius: "md",
    h: "7.75rem",
    overflow: "hidden",
    position: "relative",
  },

  "& [data-slot='sun']": {
    bg: "color-mix(in srgb, token(colors.accent.blue) 16%, transparent)",
    borderRadius: "full",
    h: "8",
    position: "absolute",
    right: "3.5rem",
    top: "1.55rem",
    w: "8",
  },

  "& [data-slot='mountain-large'], & [data-slot='mountain-small']": {
    bg: "color-mix(in srgb, token(colors.accent.blue) 18%, transparent)",
    borderRadius: "md",
    bottom: "-2.5rem",
    h: "7rem",
    position: "absolute",
    transform: "rotate(45deg)",
    w: "7rem",
  },

  "& [data-slot='mountain-large']": {
    left: "2.5rem",
  },

  "& [data-slot='mountain-small']": {
    h: "5.5rem",
    right: "2rem",
    w: "5.5rem",
  },

  "& [data-slot='page-copy']": {
    display: "grid",
    alignContent: "start",
    gap: "2.5",
    pt: "2",
  },

  "& [data-slot='line-lg'], & [data-slot='line-md'], & [data-slot='line-sm']": {
    bg: "border.subtle",
    borderRadius: "full",
    display: "block",
    h: "2.5",
  },

  "& [data-slot='line-lg']": {
    w: "80%",
  },

  "& [data-slot='line-md']": {
    w: "66%",
  },

  "& [data-slot='line-sm']": {
    w: "48%",
  },

  "& [data-slot='button-shape']": {
    bg: "accent.blue",
    borderRadius: "full",
    display: "block",
    h: "7",
    mt: "2",
    w: "6rem",
  },

  "& [data-slot='tile']": {
    bg: "color-mix(in srgb, token(colors.border.subtle) 42%, transparent)",
    borderRadius: "sm",
    display: "block",
    h: "3.75rem",
  },

  "& [data-slot='checklist-card'], & [data-slot='score-card'], & [data-slot='metrics-card']": {
    bg: "background.page",
    border: "1px solid",
    borderColor: "border.default",
    borderRadius: "lg",
    boxShadow: "0 7px 16px color-mix(in srgb, token(colors.text.primary) 5%, transparent)",
    position: "absolute",
  },

  "& [data-slot='checklist-card']": {
    left: "0",
    boxShadow: "0 8px 18px color-mix(in srgb, token(colors.text.primary) 6%, transparent)",
    p: "4.5",
    top: "7.5rem",
    w: "13.25rem",
  },

  "& [data-slot='card-title']": {
    color: "text.primary",
    fontSize: "sm",
    fontWeight: "semibold",
    lineHeight: "1.35",
    m: "0",
  },

  "& [data-slot='checklist']": {
    display: "grid",
    gap: "2.75",
    listStyle: "none",
    m: "0",
    mt: "4",
    p: "0",
  },

  "& [data-slot='checklist'] li": {
    display: "flex",
    alignItems: "center",
    gap: "2.5",
    color: "text.primary",
    fontSize: "xs",
    fontWeight: "semibold",
    lineHeight: "1.25",
  },

  "& [data-slot='checklist'] svg": {
    color: "accent.green",
    flexShrink: "0",
  },

  "& [data-slot='score-card']": {
    display: "grid",
    gap: "4",
    justifyItems: "center",
    boxShadow: "0 8px 18px color-mix(in srgb, token(colors.text.primary) 6%, transparent)",
    p: "4.5",
    right: "0",
    textAlign: "center",
    top: "8rem",
    w: "11rem",
  },

  "& [data-slot='score-ring']": {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    bg: "conic-gradient(token(colors.accent.green) 0 78%, color-mix(in srgb, token(colors.border.subtle) 55%, transparent) 78% 100%)",
    borderRadius: "full",
    color: "text.primary",
    fontSize: "2xl",
    fontWeight: "bold",
    h: "6.25rem",
    position: "relative",
    w: "6.25rem",

    _before: {
      bg: "background.page",
      borderRadius: "full",
      content: '""',
      inset: "0.45rem",
      position: "absolute",
    },
  },

  "& [data-slot='score-ring'] span": {
    zIndex: "1",
  },

  "& [data-slot='score-status'], & [data-slot='metric-status']": {
    color: "accent.green",
    fontSize: "sm",
    fontWeight: "semibold",
    lineHeight: "1.25",
    m: "0",
  },

  "& [data-slot='metrics-card']": {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    bottom: "0.5rem",
    boxShadow: "0 7px 16px color-mix(in srgb, token(colors.text.primary) 5%, transparent)",
    gap: "0",
    left: "5.75rem",
    overflow: "hidden",
    p: "3.5",
    w: "26rem",
  },

  "& [data-slot='metric']": {
    display: "grid",
    gap: "2",
    px: "3",
  },

  "& [data-slot='metric'] + [data-slot='metric']": {
    borderLeft: "1px solid",
    borderColor: "border.subtle",
  },

  "& [data-slot='metric-label']": {
    color: "text.primary",
    fontSize: "xs",
    fontWeight: "semibold",
    lineHeight: "1.25",
  },

  "& [data-slot='metric-head']": {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "3",
  },

  "& [data-slot='metric-score']": {
    color: "text.primary",
    fontSize: "sm",
    fontWeight: "bold",
    lineHeight: "1.25",
  },

  "& [data-slot='metric-bar']": {
    bg: "color-mix(in srgb, token(colors.border.subtle) 45%, transparent)",
    borderRadius: "full",
    display: "block",
    h: "2",
    overflow: "hidden",
    w: "100%",
  },

  "& [data-slot='metric-bar'] span": {
    bg: "accent.green",
    borderRadius: "full",
    display: "block",
    h: "100%",
    w: "82%",
  },

  "& [data-slot='metric']:nth-child(2) [data-slot='metric-bar'] span": {
    w: "92%",
  },

  "& [data-slot='metric']:nth-child(3) [data-slot='metric-bar'] span": {
    w: "74%",
  },
});
