import { css } from "styled-system/css";

/** Wrapper container styles generated by Panda CSS. */
export const styles = css({
  width: "min(100% - 2rem, 72rem)",
  mx: "auto",

  sm: {
    width: "min(100% - 3rem, 72rem)",
  },
});
