import { css } from "styled-system/css";

/** Page-top sentinel used to detect when the sticky header should compact. */
export const scrollSentinelStyles = css({
  position: "absolute",
  insetBlockStart: "3",
  insetInlineStart: "0",
  h: "1px",
  pointerEvents: "none",
  w: "1px",
});

/** Site header styles generated by Panda CSS. */
export const styles = css({
  position: "sticky",
  insetBlockStart: "0",
  zIndex: "20",
  borderBottom: "1px solid",
  borderColor: "border.subtle",
  bg: "background.page",
  backdropFilter: "blur(0)",
  boxShadow: "0 0 0 color-mix(in srgb, token(colors.text.primary) 0%, transparent)",
  transition:
    "background-color 180ms ease, border-color 180ms ease, box-shadow 180ms ease, backdrop-filter 180ms ease",

  "&[data-scrolled='true']": {
    borderColor: "color-mix(in srgb, token(colors.border.default) 72%, transparent)",
    bg: "color-mix(in srgb, token(colors.background.page) 88%, transparent)",
    backdropFilter: "blur(14px)",
    boxShadow: "0 5px 16px color-mix(in srgb, token(colors.text.primary) 4%, transparent)",
  },

  "& [data-slot='inner']": {
    display: "grid",
    alignItems: "center",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    columnGap: "4",
    rowGap: "0",
    py: "4",
    transition: "padding-block 180ms ease",

    sm: {
      gridTemplateColumns: "minmax(0, 1fr) auto auto",
      columnGap: "6",
    },
  },

  "&[data-scrolled='true'] [data-slot='inner']": {
    py: "2.5",
  },

  "& [data-slot='brand']": {
    display: "inline-flex",
    alignItems: "center",
    gridColumn: "1",
    gridRow: "1",
    justifySelf: "start",
    color: "text.primary",
    fontSize: "sm",
    fontWeight: "semibold",
    letterSpacing: "normal",
    lineHeight: "1.25",
    minH: "11",
    minW: "0",
    overflowWrap: "anywhere",

    _focusVisible: {
      outline: "2px solid",
      outlineColor: "accent.blue",
      outlineOffset: "3px",
    },

    sm: {
      gridColumn: "auto",
      gridRow: "auto",
    },
  },

  "& [data-slot='desktop-nav']": {
    display: "none",
    minW: "0",

    sm: {
      display: "flex",
      alignItems: "center",
      gridColumn: "auto",
      gridRow: "auto",
    },
  },

  "& [data-slot='desktop-nav-list']": {
    display: "flex",
    alignItems: "center",
    gap: "3",
    listStyle: "none",
    m: "0",
    p: "0",
  },

  "& [data-slot='desktop-link']": {
    display: "inline-flex",
    alignItems: "center",
    borderRadius: "md",
    color: "text.secondary",
    fontSize: "sm",
    fontWeight: "medium",
    lineHeight: "1.25",
    minH: "11",
    px: "2",
    py: "2",
    transition: "color 150ms ease",

    _hover: {
      color: "text.primary",
    },

    _focusVisible: {
      outline: "2px solid",
      outlineColor: "accent.blue",
      outlineOffset: "3px",
    },
  },

  "& [data-slot='desktop-cta']": {
    display: "none",
    gridColumn: "2",
    gridRow: "1",
    justifySelf: "end",

    sm: {
      display: "inline-flex",
      gridColumn: "auto",
      gridRow: "auto",
    },
  },

  "@media (prefers-reduced-motion: reduce)": {
    transition: "none",

    "& [data-slot='inner']": {
      transition: "none",
    },
  },
});
