import { css } from "styled-system/css";

/** Site header styles generated by Panda CSS. */
export const styles = css({
  borderBottom: "1px solid",
  borderColor: "gray.200",
  bg: "white",

  "& [data-slot='inner']": {
    display: "grid",
    alignItems: "center",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    columnGap: "4",
    rowGap: "0",
    py: "4",

    sm: {
      gridTemplateColumns: "auto minmax(0, 1fr) auto",
      columnGap: "6",
    },
  },

  "& [data-slot='brand']": {
    display: "inline-flex",
    alignItems: "center",
    gridColumn: "1",
    gridRow: "1",
    justifySelf: "start",
    color: "gray.950",
    fontSize: "sm",
    fontWeight: "semibold",
    letterSpacing: "normal",
    lineHeight: "1.25",
    minH: "11",
    minW: "0",
    overflowWrap: "anywhere",

    _focusVisible: {
      outline: "2px solid",
      outlineColor: "gray.950",
      outlineOffset: "3px",
    },

    sm: {
      gridColumn: "auto",
      gridRow: "auto",
    },
  },

  "& [data-slot='desktop-nav']": {
    display: "none",
    minW: "0",

    sm: {
      display: "flex",
      alignItems: "center",
      gridColumn: "auto",
      gridRow: "auto",
    },
  },

  "& [data-slot='desktop-nav-list']": {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "3",
    listStyle: "none",
    m: "0",
    p: "0",
    width: "100%",
  },

  "& [data-slot='desktop-link']": {
    display: "inline-flex",
    alignItems: "center",
    borderRadius: "md",
    color: "gray.600",
    fontSize: "sm",
    fontWeight: "medium",
    lineHeight: "1.25",
    minH: "11",
    px: "2",
    py: "2",
    transition: "color 150ms ease",

    _hover: {
      color: "gray.950",
    },

    _focusVisible: {
      outline: "2px solid",
      outlineColor: "gray.950",
      outlineOffset: "3px",
    },
  },

  "& [data-slot='cta']": {
    display: "none",
    alignItems: "center",
    justifyContent: "center",
    border: "1px solid",
    borderColor: "gray.900",
    borderRadius: "full",
    gridColumn: "2",
    gridRow: "1",
    justifySelf: "end",
    color: "gray.950",
    fontSize: "sm",
    fontWeight: "semibold",
    lineHeight: "1",
    minH: "11",
    px: "4",
    py: "2.5",
    textAlign: "center",
    whiteSpace: "nowrap",
    transition: "background-color 150ms ease, color 150ms ease",

    _hover: {
      bg: "gray.950",
      color: "white",
    },

    _focusVisible: {
      outline: "2px solid",
      outlineColor: "gray.950",
      outlineOffset: "3px",
    },

    sm: {
      display: "inline-flex",
      gridColumn: "auto",
      gridRow: "auto",
    },
  },
});
